name: CI

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Run tests
        run: npm test

# Snyk is a security tool that finds problems in your code and dependencies.
# If your project uses an old library with a known hack risk, Snyk will detect it and warn you.

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --severity-threshold=high

# Code quality issues
# Messy or hard-to-maintain code
# Duplicate code
# Unused variables
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
        