name: CI

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Run tests
        run: npm test

# Snyk is a security tool that finds problems in your code and dependencies.
# If your project uses an old library with a known hack risk, Snyk will detect it and warn you.

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --severity-threshold=high

# Code quality issues
# Messy or hard-to-maintain code
# Duplicate code
# Unused variables
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

        
      # =========================
      # 8. Start MongoDB (for tests)
      # =========================
      - name: Start MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:6
          sleep 5


       # =========================
      # 9. Build & Start App (smoke test)
      # =========================
      - name: Build & Start Server
        env:
          MONGODB_URI: mongodb://localhost:27017/test
        run: |
          npm run build
          npm start &

          for i in {1..15}; do
            curl -f http://localhost:3000/api/users/router && break
            echo "Waiting..."
            sleep 3
          done


        # =========================
      # 10. API Tests (Newman)
      # =========================
      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run ./test/TodoApp.postman_collection.json --env-var "baseUrl=http://localhost:3000"


        # =========================
      # 11. Build Docker Image (NO CACHE)
      # =========================
      - name: Build Docker image
        run: |
          docker build --no-cache \
            -t ${{ secrets.DOCKER_USERNAME }}/my-todo-app:${{ github.sha }} .
      
      